Repository NOW-SOPT-APP3-PlanFit/PlanFit-iOS, pull requests merged in 2024-05, with the labels that each got.

#3 [Config] 프로젝트 세팅
  .gitattributes
  PlanFit/PlanFit.xcodeproj/project.pbxproj
  PlanFit/PlanFit.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  PlanFit/PlanFit.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  PlanFit/PlanFit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PlanFit/PlanFit/App/AppDelegate.swift
  PlanFit/PlanFit/App/SceneDelegate.swift
  PlanFit/PlanFit/Common/Extension/NSAttributedString+.swift
  PlanFit/PlanFit/Common/Extension/UIButton+.swift
  PlanFit/PlanFit/Common/Extension/UIFont+.swift
  PlanFit/PlanFit/Common/Extension/UILabel+.swift
  PlanFit/PlanFit/Common/Extension/UIStackView+.swift
  PlanFit/PlanFit/Common/Extension/UITextField+.swift
  PlanFit/PlanFit/Common/Extension/UIView+.swift
  PlanFit/PlanFit/Common/Util/ReuseIdentifiable.swift
  PlanFit/PlanFit/Common/Util/Screen.swift
  PlanFit/PlanFit/Common/Util/Then.swift
  PlanFit/PlanFit/Presentation/Home/Controller/HomeViewController.swift
  PlanFit/PlanFit/Presentation/Home/View/HomeView.swift
  PlanFit/PlanFit/Presentation/WarmUp/Controller/WarmUpViewController.swift
  PlanFit/PlanFit/Presentation/WarmUp/View/WarmUpView.swift
  PlanFit/PlanFit/Presentation/Workout/Controller/WorkoutViewController.swift
  PlanFit/PlanFit/Presentation/Workout/View/WorkoutView.swift
  PlanFit/PlanFit/Presentation/WorkoutList/Controller/WorkoutListViewController.swift
  PlanFit/PlanFit/Presentation/WorkoutList/View/WorkoutListView.swift
  PlanFit/PlanFit/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/Contents.json
  PlanFit/PlanFit/Resource/Base.lproj/LaunchScreen.storyboard
  PlanFit/PlanFit/Resource/Info.plist
  PlanFit/PlanFit/Resource/PlanFitColor.xcassets/Contents.json
  PlanFit/PlanFit/Resource/PlanFitColor.xcassets/gray01.colorset/Contents.json
  PlanFit/PlanFit/Resource/PlanFitColor.xcassets/gray02.colorset/Contents.json
  PlanFit/PlanFit/Resource/PlanFitColor.xcassets/gray03.colorset/Contents.json
  PlanFit/PlanFit/Resource/PlanFitColor.xcassets/gray04.colorset/Contents.json
  PlanFit/PlanFit/Resource/PlanFitColor.xcassets/gray05.colorset/Contents.json
  PlanFit/PlanFit/Resource/PlanFitColor.xcassets/gray06.colorset/Contents.json
  PlanFit/PlanFit/Resource/PlanFitColor.xcassets/gray07.colorset/Contents.json
  PlanFit/PlanFit/Resource/PlanFitColor.xcassets/gray08(BG).colorset/Contents.json
  PlanFit/PlanFit/Resource/PlanFitColor.xcassets/gray09.colorset/Contents.json
  PlanFit/PlanFit/Resource/PlanFitColor.xcassets/gray10.colorset/Contents.json
  PlanFit/PlanFit/Resource/PlanFitColor.xcassets/mainGreen.colorset/Contents.json
  PlanFit/PlanFit/Resource/PlanFitColor.xcassets/subGreen01.colorset/Contents.json
  PlanFit/PlanFit/Resource/PlanFitColor.xcassets/subGreen02.colorset/Contents.json
  PlanFit/PlanFit/Resource/PlanFitColor.xcassets/subOrange01.colorset/Contents.json
  PlanFit/PlanFit/Resource/PlanFitColor.xcassets/subOrange02.colorset/Contents.json
  PlanFit/PlanFit/Resource/ViewController.swift
Labels: :wrench: Config, 🚀 진웅

#10 [Feat] 근력 운동 뷰 구현
  PlanFit/PlanFit.xcodeproj/project.pbxproj
  PlanFit/PlanFit/App/SceneDelegate.swift
  PlanFit/PlanFit/Presentation/Workout/Controller/WorkoutViewController.swift
  PlanFit/PlanFit/Presentation/Workout/Model/WorkoutData.swift
  PlanFit/PlanFit/Presentation/Workout/View/Cell/WorkoutImageCell.swift
  PlanFit/PlanFit/Presentation/Workout/View/Cell/WorkoutImageFooter.swift
  PlanFit/PlanFit/Presentation/Workout/View/Cell/WorkoutImageHeader.swift
  PlanFit/PlanFit/Presentation/Workout/View/Cell/WorkoutSetCell.swift
  PlanFit/PlanFit/Presentation/Workout/View/Cell/WorkoutSetFooter.swift
  PlanFit/PlanFit/Presentation/Workout/View/StopwatchView.swift
  PlanFit/PlanFit/Presentation/Workout/View/WorkoutView.swift
  PlanFit/PlanFit/Resource/Assets.xcassets/ellipsis.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/ellipsis.imageset/ic_ellipsis_24.svg
  PlanFit/PlanFit/Resource/Assets.xcassets/ellipsis.imageset/ic_ellipsis_24@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/ellipsis.imageset/ic_ellipsis_24@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/fab.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/fab.imageset/btn_fab.png
  PlanFit/PlanFit/Resource/Assets.xcassets/fab.imageset/btn_fab@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/fab.imageset/btn_fab@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/headphone.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/headphone.imageset/ic_headphone_24.svg
  PlanFit/PlanFit/Resource/Assets.xcassets/headphone.imageset/ic_headphone_24@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/headphone.imageset/ic_headphone_24@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/heart.fill.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/heart.fill.imageset/Property 1=ic_heart_active_16.png
  PlanFit/PlanFit/Resource/Assets.xcassets/heart.fill.imageset/Property 1=ic_heart_active_16@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/heart.fill.imageset/Property 1=ic_heart_active_16@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/latpulldown.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/latpulldown.imageset/_gif_exc_latpulldown.png
  PlanFit/PlanFit/Resource/Assets.xcassets/latpulldown.imageset/_gif_exc_latpulldown@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/latpulldown.imageset/_gif_exc_latpulldown@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/noOnairDot.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/noOnairDot.imageset/Property 1=ic_onair_inactive_16.png
  PlanFit/PlanFit/Resource/Assets.xcassets/noOnairDot.imageset/Property 1=ic_onair_inactive_16@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/noOnairDot.imageset/Property 1=ic_onair_inactive_16@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/onairDot.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/onairDot.imageset/Property 1=ic_onair_active_16.svg
  PlanFit/PlanFit/Resource/Assets.xcassets/onairDot.imageset/Property 1=ic_onair_active_16@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/onairDot.imageset/Property 1=ic_onair_active_16@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/pause.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/pause.imageset/ic_pause_16.png
  PlanFit/PlanFit/Resource/Assets.xcassets/pause.imageset/ic_pause_16@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/pause.imageset/ic_pause_16@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/pencil.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/pencil.imageset/ic_pencil_16.png
  PlanFit/PlanFit/Resource/Assets.xcassets/pencil.imageset/ic_pencil_16@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/pencil.imageset/ic_pencil_16@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/play.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/play.imageset/ic_play_16.svg
  PlanFit/PlanFit/Resource/Assets.xcassets/play.imageset/ic_play_16@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/play.imageset/ic_play_16@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/plus.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/plus.imageset/ic_plus_16.png
  PlanFit/PlanFit/Resource/Assets.xcassets/plus.imageset/ic_plus_16@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/plus.imageset/ic_plus_16@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/slash.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/slash.imageset/Property 1=ic_slash_active_16.png
  PlanFit/PlanFit/Resource/Assets.xcassets/slash.imageset/Property 1=ic_slash_active_16@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/slash.imageset/Property 1=ic_slash_active_16@3x.png
Labels: :sparkles: Feat, 🏋️‍♂️ 정빈

#14 [Feat/#8] 추천 운동 리스트 화면 UI 구현
  PlanFit/PlanFit.xcodeproj/project.pbxproj
  PlanFit/PlanFit/Common/Extension/UILabel+.swift
  PlanFit/PlanFit/Presentation/WorkoutList/Controller/WorkoutListViewController.swift
  PlanFit/PlanFit/Presentation/WorkoutList/View/WorkoutListFooter.swift
  PlanFit/PlanFit/Presentation/WorkoutList/View/WorkoutListHeader.swift
  PlanFit/PlanFit/Presentation/WorkoutList/View/WorkoutListModel.swift
  PlanFit/PlanFit/Presentation/WorkoutList/View/WorkoutListNavigation.swift
  PlanFit/PlanFit/Presentation/WorkoutList/View/WorkoutListView.swift
  PlanFit/PlanFit/Presentation/WorkoutList/View/WorkoutListViewCell.swift
  PlanFit/PlanFit/Resource/Assets.xcassets/arrowTop.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/arrowTop.imageset/ic_arrow_top_24.svg
  PlanFit/PlanFit/Resource/Assets.xcassets/buttonBackGradiant.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/buttonBackGradiant.imageset/Frame 8680.png
  PlanFit/PlanFit/Resource/Assets.xcassets/buttonBackGradiant.imageset/Frame 8680@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/buttonBackGradiant.imageset/Frame 8680@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/chestpress.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/chestpress.imageset/img_exc_chestpress.png
  PlanFit/PlanFit/Resource/Assets.xcassets/chestpress.imageset/img_exc_chestpress@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/chestpress.imageset/img_exc_chestpress@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/clock.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/clock.imageset/ic_clock_16.svg
  PlanFit/PlanFit/Resource/Assets.xcassets/dumbellcurl.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/dumbellcurl.imageset/img_exc_dumbellcurl.png
  PlanFit/PlanFit/Resource/Assets.xcassets/dumbellcurl.imageset/img_exc_dumbellcurl@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/dumbellcurl.imageset/img_exc_dumbellcurl@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/dumbelllunge.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/dumbelllunge.imageset/img_exc_dumbelllunge.png
  PlanFit/PlanFit/Resource/Assets.xcassets/dumbelllunge.imageset/img_exc_dumbelllunge@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/dumbelllunge.imageset/img_exc_dumbelllunge@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/dumbellraise.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/dumbellraise.imageset/img_exc_dumbellraise.png
  PlanFit/PlanFit/Resource/Assets.xcassets/dumbellraise.imageset/img_exc_dumbellraise@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/dumbellraise.imageset/img_exc_dumbellraise@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/hamburger.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/hamburger.imageset/ic_hamburger_24.svg
  PlanFit/PlanFit/Resource/Assets.xcassets/seperator.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/seperator.imageset/seperate.svg
  PlanFit/PlanFit/Resource/Assets.xcassets/share.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/share.imageset/ic_share_24.svg
  PlanFit/PlanFit/Resource/Assets.xcassets/stretching.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/stretching.imageset/img_exc_stretching.png
  PlanFit/PlanFit/Resource/Assets.xcassets/stretching.imageset/img_exc_stretching@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/stretching.imageset/img_exc_stretching@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/treadmill.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/treadmill.imageset/img_exc_treadmill.png
  PlanFit/PlanFit/Resource/Assets.xcassets/treadmill.imageset/img_exc_treadmill@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/treadmill.imageset/img_exc_treadmill@3x.png
Labels: :sparkles: Feat, 🍔 수연

#16 [Feat/#15] 홈 화면에서 운동리스트 화면 이동 구현하기
  PlanFit/PlanFit/App/SceneDelegate.swift
  PlanFit/PlanFit/Presentation/Home/Controller/ExerciseViewController.swift
  PlanFit/PlanFit/Presentation/Home/Controller/HomeTabBarController.swift
  PlanFit/PlanFit/Presentation/Home/View/ExerciseInfoBannerView.swift
  PlanFit/PlanFit/Presentation/Home/View/StartExerciseBannerView.swift
  PlanFit/PlanFit/Presentation/WorkoutList/Controller/WorkoutListViewController.swift
  PlanFit/PlanFit/Presentation/WorkoutList/View/WorkoutListNavigation.swift
  PlanFit/PlanFit/Presentation/WorkoutList/View/WorkoutListView.swift
Labels: :sparkles: Feat, 🚀 진웅

#18 [Feat/#13] 운동 스트레칭 (웜업) 화면 구현
  PlanFit/PlanFit.xcodeproj/project.pbxproj
  PlanFit/PlanFit/Presentation/WarmUp/Controller/WarmUpViewController.swift
  PlanFit/PlanFit/Presentation/WarmUp/View/PauseButton.swift
  PlanFit/PlanFit/Presentation/WarmUp/View/WarmUpView.swift
  PlanFit/PlanFit/Presentation/Workout/Controller/WorkoutViewController.swift
  PlanFit/PlanFit/Presentation/Workout/View/StopwatchView.swift
  PlanFit/PlanFit/Resource/Assets.xcassets/cycle.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/cycle.imageset/cycle.png
  PlanFit/PlanFit/Resource/Assets.xcassets/cycle.imageset/cycle@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/cycle.imageset/cycle@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/pauseBig.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/pauseBig.imageset/pauseBig.png
  PlanFit/PlanFit/Resource/Assets.xcassets/pauseBig.imageset/pauseBig@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/pauseBig.imageset/pauseBig@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/playBig.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/playBig.imageset/playBig.png
  PlanFit/PlanFit/Resource/Assets.xcassets/playBig.imageset/playBig@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/playBig.imageset/playBig@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/playnext.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/playnext.imageset/playnext.png
  PlanFit/PlanFit/Resource/Assets.xcassets/playnext.imageset/playnext@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/playnext.imageset/playnext@3x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/reverse.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/reverse.imageset/reverse.png
  PlanFit/PlanFit/Resource/Assets.xcassets/reverse.imageset/reverse@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/reverse.imageset/reverse@3x.png
Labels: :sparkles: Feat, 🚀 진웅

#19 [Config/#12] NetworkSetting
  PlanFit/PlanFit.xcodeproj/project.pbxproj
  PlanFit/PlanFit/Network/Config.swift
  PlanFit/PlanFit/Network/MoyaLoggingPlugin.swift
  PlanFit/PlanFit/Network/NetworkResult.swift
  PlanFit/PlanFit/Network/RequestModel/PlanOptionsRequestModel.swift
  PlanFit/PlanFit/Network/RequestModel/WorkoutListRequestModel.swift
  PlanFit/PlanFit/Network/ResponseModel/GeneralResponseModel.swift
  PlanFit/PlanFit/Network/ResponseModel/PlanOptionsResponseModel.swift
  PlanFit/PlanFit/Network/ResponseModel/WorkoutListResponseModel.swift
  PlanFit/PlanFit/Network/WorkoutService.swift
  PlanFit/PlanFit/Network/WorkoutTargetType.swift
  PlanFit/PlanFit/Resource/Info.plist
Labels: :sparkles: Feat, 🏋️‍♂️ 정빈

#23 [Feat/#9] 근력 운동 View 네트워크 연결
  PlanFit/PlanFit/Presentation/Workout/Controller/WorkoutViewController.swift
  PlanFit/PlanFit/Presentation/Workout/View/Cell/WorkoutImageHeader.swift
  PlanFit/PlanFit/Resource/Assets.xcassets/heart.empty.imageset/Contents.json
  PlanFit/PlanFit/Resource/Assets.xcassets/heart.empty.imageset/Property 1=ic_heart_inactive_16.svg
  PlanFit/PlanFit/Resource/Assets.xcassets/heart.empty.imageset/Property 1=ic_heart_inactive_16@2x.png
  PlanFit/PlanFit/Resource/Assets.xcassets/heart.empty.imageset/Property 1=ic_heart_inactive_16@3x.png
Labels: :sparkles: Feat, 🏋️‍♂️ 정빈

#25 [Feat/#21] 추천 운동 리스트 화면 API 연결
  PlanFit/PlanFit/Presentation/WorkoutList/Controller/WorkoutListViewController.swift
  PlanFit/PlanFit/Presentation/WorkoutList/Model/WorkoutListModel.swift
  PlanFit/PlanFit/Presentation/WorkoutList/View/WorkoutListViewCell.swift
Labels: :sparkles: Feat, 🍔 수연

#27 [Feat/#22] 홈 화면 네트워크 구현
  PlanFit/PlanFit/Presentation/Home/Controller/ExerciseViewController.swift
  PlanFit/PlanFit/Presentation/Home/Model/BodyConditionModel.swift
  PlanFit/PlanFit/Presentation/Home/Model/WorkoutTimeModel.swift
  PlanFit/PlanFit/Presentation/Home/View/ExerciseRootView.swift
  PlanFit/PlanFit/Presentation/Home/View/StartExerciseBannerView.swift
Labels: :sparkles: Feat, 🚀 진웅

#29 [Feat/#24] NavigationBar 내의 Stopwatch 구현
  PlanFit/PlanFit/Presentation/Workout/View/StopwatchView.swift
Labels: :sparkles: Feat, 🏋️‍♂️ 정빈

#30 [Refactor/#28] 네비게이션 바의 백 버튼 숨기기
  PlanFit/PlanFit/Presentation/WorkoutList/Controller/WorkoutListViewController.swift
Labels: :recycle: Refactor, 🚀 진웅

#32 [Fix/#26] 네트워크 없이 수행 가능한 더미 데이터 삽입
  PlanFit/PlanFit/Presentation/WorkoutList/Controller/WorkoutListViewController.swift
Labels: :rotating_light: Fix, 🍔 수연

#33 [Chore/#31] 앱 동작 검사 및 사소한 수정 반영
  PlanFit/PlanFit/Common/Extension/UIFont+.swift
  PlanFit/PlanFit/Presentation/Workout/View/StopwatchView.swift
  PlanFit/PlanFit/Resource/ViewController.swift
Labels: :poop: Chore, 🚀 진웅
